pip freeopenapi: 3.0.3
info:
  title: Your Project API
  version: 1.0.0
  description: Your project description
paths:
  /caretakers/:
    get:
      operationId: caretakers_retrieve
      tags:
      - caretakers
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: caretakers_create
      tags:
      - caretakers
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /caretakers/{id}:
    get:
      operationId: caretakers_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - caretakers
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: caretakers_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - caretakers
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: caretakers_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - caretakers
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /caretakers_ordered_years_experience/:
    get:
      operationId: caretakers_ordered_years_experience_retrieve
      tags:
      - caretakers_ordered_years_experience
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /departments/:
    get:
      operationId: departments_retrieve
      tags:
      - departments
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: departments_create
      tags:
      - departments
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /departments/{id}:
    get:
      operationId: departments_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - departments
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: departments_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - departments
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: departments_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - departments
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /departments_ordered_by_caretakers/:
    get:
      operationId: departments_ordered_by_caretakers_retrieve
      tags:
      - departments_ordered_by_caretakers
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /shelteredanimals/:
    get:
      operationId: shelteredanimals_retrieve
      tags:
      - shelteredanimals
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: shelteredanimals_create
      tags:
      - shelteredanimals
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /shelteredanimals/{id}:
    get:
      operationId: shelteredanimals_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shelteredanimals
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: shelteredanimals_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shelteredanimals
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: shelteredanimals_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shelteredanimals
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /shelteredanimals/{id}/caretakers:
    post:
      operationId: shelteredanimals_caretakers_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shelteredanimals
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /takecare/:
    get:
      operationId: takecare_retrieve
      tags:
      - takecare
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: takecare_create
      tags:
      - takecare
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /takecare/{id}:
    get:
      operationId: takecare_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - takecare
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: takecare_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - takecare
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: takecare_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - takecare
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
