# Generated by Django 4.1.7 on 2023-04-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalshelter', '0003_alter_takecare_animal_alter_takecare_caretaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelteredanimals',
            name='description',
            field=models.CharField(default='no description', max_length=20000),
        ),
    ]
